--[[
Animo metadata
Generated by Animo Spriteloq: Lanica's Flash SWF to sprite sheet exporter (c) Lanica, Inc. 2012, (c) Loqheart 2012 
version 1.0.9
target Corona SDK
extension lua
exportName sheet
exportPath file:///Users/elliot/Code/dirtbikerun/test
sheetSize 256x128
msFactor 1000
sources 1
name; url; referencePoint; startFrame; totalFrames; frameRate; topLeft; bottomRight; sourceRect; loopParam; includeReverse; rasterize
charDogBlue; ../../trailer-park-wars/animations/characters/charDogBlue.swf; (x=0, y=0); 1; 10; 30; (x=254, y=161); (x=288, y=219); (x=252, y=159, w=38, h=62); 1; false; false
assetShapes 0
]]

local sheet = false
local setInfo = false
local msFactor = 1000

local function newSpriteSet(_sheet, _name, _startFrame, _frameCount, _frameRate, _loopParam, _xReference, _yReference, _spriteSourceWidth, _spriteSourceHeight, _unscaledSpriteX, _unscaledSpriteY, _unscaledSpriteWidth, _unscaledSpriteHeight, _frames, _shapeOnly)
    if (_shapeOnly) then
        return
    end

    local set = sprite.newSpriteSet(_sheet, _startFrame, _frameCount)
    sprite.add(set, _name, 1, _frameCount, (_frameCount / _frameRate) * msFactor, _loopParam)
    setInfo[_name] = {set = set, xReference = _xReference, yReference = _yReference, spriteSourceSize = {width = _spriteSourceWidth, height = _spriteSourceHeight}, unscaledSpriteRect = {x = _unscaledSpriteX, y = _unscaledSpriteY, width = _unscaledSpriteWidth, height = _unscaledSpriteHeight}, frames = _frames, frameRate = _frameRate, frameCount = _frameCount, fpss = _frameRate / 1000, startFrame = _startFrame}
end

local function load()
    local frameSets = {}
    local allFrames = {}

    frameSets["charDogBlue"] = {
        {
            name="charDogBlue-1",
            spriteColorRect={x=0, y=0},
            textureRect={x=0, y=0, width=38, height=62},
            spriteSourceSize={width=38, height=62},
            spriteTrimmed=false,
        },
        {
            name="charDogBlue-2",
            spriteColorRect={x=0, y=1},
            textureRect={x=0, y=62, width=38, height=61},
            spriteSourceSize={width=38, height=62},
            spriteTrimmed=true,
        },
        {
            name="charDogBlue-3",
            spriteColorRect={x=0, y=2},
            textureRect={x=76, y=0, width=38, height=60},
            spriteSourceSize={width=38, height=62},
            spriteTrimmed=true,
        },
        {
            name="charDogBlue-4",
            spriteColorRect={x=0, y=3},
            textureRect={x=76, y=60, width=38, height=59},
            spriteSourceSize={width=38, height=62},
            spriteTrimmed=true,
        },
        {
            name="charDogBlue-5",
            spriteColorRect={x=0, y=4},
            textureRect={x=114, y=58, width=38, height=58},
            spriteSourceSize={width=38, height=62},
            spriteTrimmed=true,
        },
        {
            name="charDogBlue-6",
            spriteColorRect={x=0, y=5},
            textureRect={x=152, y=0, width=38, height=57},
            spriteSourceSize={width=38, height=62},
            spriteTrimmed=true,
        },
        {
            name="charDogBlue-7",
            spriteColorRect={x=0, y=4},
            textureRect={x=114, y=0, width=38, height=58},
            spriteSourceSize={width=38, height=62},
            spriteTrimmed=true,
        },
        {
            name="charDogBlue-8",
            spriteColorRect={x=0, y=2},
            textureRect={x=38, y=61, width=38, height=60},
            spriteSourceSize={width=38, height=62},
            spriteTrimmed=true,
        },
        {
            name="charDogBlue-9",
            spriteColorRect={x=0, y=1},
            textureRect={x=38, y=0, width=38, height=61},
            spriteSourceSize={width=38, height=62},
            spriteTrimmed=true,
        },
        {
            name="charDogBlue-10",
            spriteColorRect={x=0, y=0},
            textureRect={x=0, y=0, width=38, height=62},
            spriteSourceSize={width=38, height=62},
            spriteTrimmed=false,
        }
    }
    allFrames = table.copy(allFrames, frameSets["charDogBlue"])


    sheet = sprite.newSpriteSheetFromData("sheet.png", {frames = allFrames })

    -- setInfo table contains info about sprites: { (spriteName = {set: set, xReference: xReference, yReference: yReference, spriteSourceSize = {width: width, height: height}})+ }
    setInfo = {}
    newSpriteSet(sheet, "charDogBlue", 1, 10, 30, 1, 0 - (38/2 + 252), 0 - (62/2 + 159), 38, 62, 0, 0, 38, 62, frameSets["charDogBlue"], false)

    local shapes = {}
    shapes["charDogBlue"] = {

    }

    return { sheet = sheet, setInfo = setInfo, shapes = shapes }
end

local function destroy()
    sheet:dispose()
    sheet = nil
    setInfo = nil
end

return { load = load, destroy = destroy }
