-- This file is for use with Corona Game Edition
-- 
-- The function getSpriteSheetData() returns a table suitable for importing using sprite.newSpriteSheetFromData()
-- 
-- This file is automatically generated with TexturePacker (http://www.codeandweb.com/texturepacker). Do not edit
-- $TexturePacker:SmartUpdate:e3a27cbc45ac84a0fb0adb3a47287b9c:cfb34e7932e0b99e9ca9dce95825a837:6b88a53a9e73117e29a046488177ecc4$
-- 
-- Usage example:
--        local sheetData = require "ThisFile.lua"
--        local data = sheetData.getSpriteSheetData()
--        local spriteSheet = sprite.newSpriteSheetFromData( "Untitled", data )
-- 
-- For more details, see http://developer.anscamobile.com/content/game-edition-sprite-sheets

local SpriteSheet = {}
SpriteSheet.getSpriteSheetData = function ()
	return {
		frames = {
			{
				name = "1.png",
				spriteColorRect = { x = 0, y = 0, width = 28, height = 50 },
				textureRect = { x = 2, y = 2, width = 28, height = 50 },
				spriteSourceSize = { width = 28, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "2.png",
				spriteColorRect = { x = 0, y = 0, width = 42, height = 50 },
				textureRect = { x = 32, y = 2, width = 42, height = 50 },
				spriteSourceSize = { width = 42, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "3.png",
				spriteColorRect = { x = 0, y = 0, width = 39, height = 50 },
				textureRect = { x = 76, y = 2, width = 39, height = 50 },
				spriteSourceSize = { width = 39, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "4.png",
				spriteColorRect = { x = 0, y = 0, width = 43, height = 50 },
				textureRect = { x = 117, y = 2, width = 43, height = 50 },
				spriteSourceSize = { width = 43, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "5.png",
				spriteColorRect = { x = 0, y = 0, width = 40, height = 50 },
				textureRect = { x = 162, y = 2, width = 40, height = 50 },
				spriteSourceSize = { width = 40, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "6.png",
				spriteColorRect = { x = 0, y = 0, width = 41, height = 50 },
				textureRect = { x = 204, y = 2, width = 41, height = 50 },
				spriteSourceSize = { width = 41, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "7.png",
				spriteColorRect = { x = 0, y = 0, width = 39, height = 50 },
				textureRect = { x = 247, y = 2, width = 39, height = 50 },
				spriteSourceSize = { width = 39, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "8.png",
				spriteColorRect = { x = 0, y = 0, width = 39, height = 50 },
				textureRect = { x = 288, y = 2, width = 39, height = 50 },
				spriteSourceSize = { width = 39, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "9.png",
				spriteColorRect = { x = 0, y = 0, width = 39, height = 50 },
				textureRect = { x = 329, y = 2, width = 39, height = 50 },
				spriteSourceSize = { width = 39, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "0.png",
				spriteColorRect = { x = 0, y = 0, width = 40, height = 50 },
				textureRect = { x = 370, y = 2, width = 40, height = 50 },
				spriteSourceSize = { width = 40, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "dot.png",
				spriteColorRect = { x = 0, y = 0, width = 17, height = 50 },
				textureRect = { x = 412, y = 2, width = 17, height = 50 },
				spriteSourceSize = { width = 17, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "m.png",
				spriteColorRect = { x = 0, y = 0, width = 55, height = 50 },
				textureRect = { x = 431, y = 2, width = 55, height = 50 },
				spriteSourceSize = { width = 55, height = 50 },
				spriteTrimmed = false,
				textureRotated = false
			},
		}
	}
end
return SpriteSheet

