-- This file is for use with Corona Game Edition
-- 
-- The function getSpriteSheetData() returns a table suitable for importing using sprite.newSpriteSheetFromData()
-- 
-- This file is automatically generated with TexturePacker (http://www.codeandweb.com/texturepacker). Do not edit
-- $TexturePacker:SmartUpdate:05411081e4917988a579ad8b3d6c6b9a:d764b12a22d0277a44e1b1d12881fe30:90a6acd6f275b7885e4d408321846cb1$
-- 
-- Usage example:
--        local sheetData = require "ThisFile.lua"
--        local data = sheetData.getSpriteSheetData()
--        local spriteSheet = sprite.newSpriteSheetFromData( "Untitled.png", data )
-- 
-- For more details, see http://developer.anscamobile.com/content/game-edition-sprite-sheets

local SpriteSheet = {}
SpriteSheet.getSpriteSheetData = function ()
	return {
		frames = {
			{
				name = "exo_01.png",
				spriteColorRect = { x = 0, y = 0, width = 58, height = 79 },
				textureRect = { x = 2, y = 2, width = 58, height = 79 },
				spriteSourceSize = { width = 58, height = 79 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "exo_02.png",
				spriteColorRect = { x = 0, y = 0, width = 51, height = 79 },
				textureRect = { x = 62, y = 2, width = 51, height = 79 },
				spriteSourceSize = { width = 51, height = 79 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "exo_03.png",
				spriteColorRect = { x = 0, y = 0, width = 48, height = 79 },
				textureRect = { x = 115, y = 2, width = 48, height = 79 },
				spriteSourceSize = { width = 48, height = 79 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "exo_04.png",
				spriteColorRect = { x = 0, y = 0, width = 52, height = 79 },
				textureRect = { x = 165, y = 2, width = 52, height = 79 },
				spriteSourceSize = { width = 52, height = 79 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "exo_05.png",
				spriteColorRect = { x = 0, y = 0, width = 48, height = 79 },
				textureRect = { x = 219, y = 2, width = 48, height = 79 },
				spriteSourceSize = { width = 48, height = 79 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "exo_06.png",
				spriteColorRect = { x = 0, y = 0, width = 46, height = 79 },
				textureRect = { x = 269, y = 2, width = 46, height = 79 },
				spriteSourceSize = { width = 46, height = 79 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "exo_07.png",
				spriteColorRect = { x = 0, y = 0, width = 52, height = 79 },
				textureRect = { x = 317, y = 2, width = 52, height = 79 },
				spriteSourceSize = { width = 52, height = 79 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "exo_08.png",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 79 },
				textureRect = { x = 371, y = 2, width = 50, height = 79 },
				spriteSourceSize = { width = 50, height = 79 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "exo_09.png",
				spriteColorRect = { x = 0, y = 0, width = 25, height = 79 },
				textureRect = { x = 423, y = 2, width = 25, height = 79 },
				spriteSourceSize = { width = 25, height = 79 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "exo_10.png",
				spriteColorRect = { x = 0, y = 0, width = 34, height = 79 },
				textureRect = { x = 450, y = 2, width = 34, height = 79 },
				spriteSourceSize = { width = 34, height = 79 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "exo_11.png",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 79 },
				textureRect = { x = 486, y = 2, width = 50, height = 79 },
				spriteSourceSize = { width = 50, height = 79 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "exo_12.png",
				spriteColorRect = { x = 0, y = 0, width = 45, height = 79 },
				textureRect = { x = 538, y = 2, width = 45, height = 79 },
				spriteSourceSize = { width = 45, height = 79 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "exo_13.png",
				spriteColorRect = { x = 0, y = 0, width = 68, height = 79 },
				textureRect = { x = 585, y = 2, width = 68, height = 79 },
				spriteSourceSize = { width = 68, height = 79 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "exo_14.png",
				spriteColorRect = { x = 0, y = 0, width = 56, height = 79 },
				textureRect = { x = 655, y = 2, width = 56, height = 79 },
				spriteSourceSize = { width = 56, height = 79 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "exo_15.png",
				spriteColorRect = { x = 0, y = 0, width = 54, height = 79 },
				textureRect = { x = 713, y = 2, width = 54, height = 79 },
				spriteSourceSize = { width = 54, height = 79 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "exo_16.png",
				spriteColorRect = { x = 0, y = 0, width = 48, height = 79 },
				textureRect = { x = 769, y = 2, width = 48, height = 79 },
				spriteSourceSize = { width = 48, height = 79 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "exo_17.png",
				spriteColorRect = { x = 0, y = 0, width = 56, height = 79 },
				textureRect = { x = 819, y = 2, width = 56, height = 79 },
				spriteSourceSize = { width = 56, height = 79 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "exo_18.png",
				spriteColorRect = { x = 0, y = 0, width = 49, height = 79 },
				textureRect = { x = 877, y = 2, width = 49, height = 79 },
				spriteSourceSize = { width = 49, height = 79 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "exo_19.png",
				spriteColorRect = { x = 0, y = 0, width = 48, height = 79 },
				textureRect = { x = 928, y = 2, width = 48, height = 79 },
				spriteSourceSize = { width = 48, height = 79 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "exo_20.png",
				spriteColorRect = { x = 0, y = 0, width = 48, height = 79 },
				textureRect = { x = 978, y = 2, width = 48, height = 79 },
				spriteSourceSize = { width = 48, height = 79 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "exo_21.png",
				spriteColorRect = { x = 0, y = 0, width = 54, height = 79 },
				textureRect = { x = 1028, y = 2, width = 54, height = 79 },
				spriteSourceSize = { width = 54, height = 79 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "exo_22.png",
				spriteColorRect = { x = 0, y = 0, width = 56, height = 79 },
				textureRect = { x = 1084, y = 2, width = 56, height = 79 },
				spriteSourceSize = { width = 56, height = 79 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "exo_23.png",
				spriteColorRect = { x = 0, y = 0, width = 78, height = 79 },
				textureRect = { x = 1142, y = 2, width = 78, height = 79 },
				spriteSourceSize = { width = 78, height = 79 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "exo_24.png",
				spriteColorRect = { x = 0, y = 0, width = 53, height = 79 },
				textureRect = { x = 1222, y = 2, width = 53, height = 79 },
				spriteSourceSize = { width = 53, height = 79 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "exo_25.png",
				spriteColorRect = { x = 0, y = 0, width = 51, height = 79 },
				textureRect = { x = 1277, y = 2, width = 51, height = 79 },
				spriteSourceSize = { width = 51, height = 79 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "exo_26.png",
				spriteColorRect = { x = 0, y = 0, width = 52, height = 79 },
				textureRect = { x = 1330, y = 2, width = 52, height = 79 },
				spriteSourceSize = { width = 52, height = 79 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "exo_29.png",
				spriteColorRect = { x = 0, y = 0, width = 46, height = 84 },
				textureRect = { x = 1384, y = 2, width = 46, height = 84 },
				spriteSourceSize = { width = 46, height = 84 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "exo_30.png",
				spriteColorRect = { x = 0, y = 0, width = 47, height = 84 },
				textureRect = { x = 1432, y = 2, width = 47, height = 84 },
				spriteSourceSize = { width = 47, height = 84 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "exo_31.png",
				spriteColorRect = { x = 0, y = 0, width = 40, height = 84 },
				textureRect = { x = 1481, y = 2, width = 40, height = 84 },
				spriteSourceSize = { width = 40, height = 84 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "exo_32.png",
				spriteColorRect = { x = 0, y = 0, width = 47, height = 84 },
				textureRect = { x = 1523, y = 2, width = 47, height = 84 },
				spriteSourceSize = { width = 47, height = 84 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "exo_33.png",
				spriteColorRect = { x = 0, y = 0, width = 44, height = 84 },
				textureRect = { x = 1572, y = 2, width = 44, height = 84 },
				spriteSourceSize = { width = 44, height = 84 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "exo_34.png",
				spriteColorRect = { x = 0, y = 0, width = 36, height = 84 },
				textureRect = { x = 1618, y = 2, width = 36, height = 84 },
				spriteSourceSize = { width = 36, height = 84 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "exo_35.png",
				spriteColorRect = { x = 0, y = 0, width = 46, height = 84 },
				textureRect = { x = 2, y = 88, width = 46, height = 84 },
				spriteSourceSize = { width = 46, height = 84 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "exo_36.png",
				spriteColorRect = { x = 0, y = 0, width = 44, height = 84 },
				textureRect = { x = 50, y = 88, width = 44, height = 84 },
				spriteSourceSize = { width = 44, height = 84 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "exo_37.png",
				spriteColorRect = { x = 0, y = 0, width = 26, height = 84 },
				textureRect = { x = 96, y = 88, width = 26, height = 84 },
				spriteSourceSize = { width = 26, height = 84 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "exo_38.png",
				spriteColorRect = { x = 0, y = 0, width = 23, height = 84 },
				textureRect = { x = 124, y = 88, width = 23, height = 84 },
				spriteSourceSize = { width = 23, height = 84 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "exo_39.png",
				spriteColorRect = { x = 0, y = 0, width = 46, height = 84 },
				textureRect = { x = 149, y = 88, width = 46, height = 84 },
				spriteSourceSize = { width = 46, height = 84 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "exo_40.png",
				spriteColorRect = { x = 0, y = 0, width = 30, height = 84 },
				textureRect = { x = 197, y = 88, width = 30, height = 84 },
				spriteSourceSize = { width = 30, height = 84 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "exo_41.png",
				spriteColorRect = { x = 0, y = 0, width = 69, height = 84 },
				textureRect = { x = 229, y = 88, width = 69, height = 84 },
				spriteSourceSize = { width = 69, height = 84 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "exo_42.png",
				spriteColorRect = { x = 0, y = 0, width = 46, height = 84 },
				textureRect = { x = 300, y = 88, width = 46, height = 84 },
				spriteSourceSize = { width = 46, height = 84 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "exo_43.png",
				spriteColorRect = { x = 0, y = 0, width = 46, height = 84 },
				textureRect = { x = 348, y = 88, width = 46, height = 84 },
				spriteSourceSize = { width = 46, height = 84 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "exo_44.png",
				spriteColorRect = { x = 0, y = 0, width = 47, height = 84 },
				textureRect = { x = 396, y = 88, width = 47, height = 84 },
				spriteSourceSize = { width = 47, height = 84 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "exo_45.png",
				spriteColorRect = { x = 0, y = 0, width = 47, height = 84 },
				textureRect = { x = 445, y = 88, width = 47, height = 84 },
				spriteSourceSize = { width = 47, height = 84 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "exo_46.png",
				spriteColorRect = { x = 0, y = 0, width = 38, height = 84 },
				textureRect = { x = 494, y = 88, width = 38, height = 84 },
				spriteSourceSize = { width = 38, height = 84 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "exo_47.png",
				spriteColorRect = { x = 0, y = 0, width = 41, height = 84 },
				textureRect = { x = 534, y = 88, width = 41, height = 84 },
				spriteSourceSize = { width = 41, height = 84 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "exo_48.png",
				spriteColorRect = { x = 0, y = 0, width = 35, height = 84 },
				textureRect = { x = 577, y = 88, width = 35, height = 84 },
				spriteSourceSize = { width = 35, height = 84 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "exo_49.png",
				spriteColorRect = { x = 0, y = 0, width = 46, height = 84 },
				textureRect = { x = 614, y = 88, width = 46, height = 84 },
				spriteSourceSize = { width = 46, height = 84 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "exo_50.png",
				spriteColorRect = { x = 0, y = 0, width = 48, height = 84 },
				textureRect = { x = 662, y = 88, width = 48, height = 84 },
				spriteSourceSize = { width = 48, height = 84 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "exo_51.png",
				spriteColorRect = { x = 0, y = 0, width = 65, height = 84 },
				textureRect = { x = 712, y = 88, width = 65, height = 84 },
				spriteSourceSize = { width = 65, height = 84 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "exo_52.png",
				spriteColorRect = { x = 0, y = 0, width = 48, height = 84 },
				textureRect = { x = 779, y = 88, width = 48, height = 84 },
				spriteSourceSize = { width = 48, height = 84 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "exo_53.png",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 84 },
				textureRect = { x = 829, y = 88, width = 50, height = 84 },
				spriteSourceSize = { width = 50, height = 84 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "exo_54.png",
				spriteColorRect = { x = 0, y = 0, width = 43, height = 84 },
				textureRect = { x = 881, y = 88, width = 43, height = 84 },
				spriteSourceSize = { width = 43, height = 84 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "exo_56.png",
				spriteColorRect = { x = 0, y = 0, width = 35, height = 71 },
				textureRect = { x = 926, y = 88, width = 35, height = 71 },
				spriteSourceSize = { width = 35, height = 71 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "exo_57.png",
				spriteColorRect = { x = 0, y = 0, width = 48, height = 71 },
				textureRect = { x = 963, y = 88, width = 48, height = 71 },
				spriteSourceSize = { width = 48, height = 71 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "exo_58.png",
				spriteColorRect = { x = 0, y = 0, width = 50, height = 71 },
				textureRect = { x = 1013, y = 88, width = 50, height = 71 },
				spriteSourceSize = { width = 50, height = 71 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "exo_59.png",
				spriteColorRect = { x = 0, y = 0, width = 52, height = 71 },
				textureRect = { x = 1065, y = 88, width = 52, height = 71 },
				spriteSourceSize = { width = 52, height = 71 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "exo_60.png",
				spriteColorRect = { x = 0, y = 0, width = 48, height = 71 },
				textureRect = { x = 1119, y = 88, width = 48, height = 71 },
				spriteSourceSize = { width = 48, height = 71 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "exo_61.png",
				spriteColorRect = { x = 0, y = 0, width = 48, height = 71 },
				textureRect = { x = 1169, y = 88, width = 48, height = 71 },
				spriteSourceSize = { width = 48, height = 71 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "exo_62.png",
				spriteColorRect = { x = 0, y = 0, width = 48, height = 71 },
				textureRect = { x = 1219, y = 88, width = 48, height = 71 },
				spriteSourceSize = { width = 48, height = 71 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "exo_63.png",
				spriteColorRect = { x = 0, y = 0, width = 51, height = 71 },
				textureRect = { x = 1269, y = 88, width = 51, height = 71 },
				spriteSourceSize = { width = 51, height = 71 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "exo_64.png",
				spriteColorRect = { x = 0, y = 0, width = 53, height = 71 },
				textureRect = { x = 1322, y = 88, width = 53, height = 71 },
				spriteSourceSize = { width = 53, height = 71 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "exo_65.png",
				spriteColorRect = { x = 0, y = 0, width = 51, height = 71 },
				textureRect = { x = 1377, y = 88, width = 51, height = 71 },
				spriteSourceSize = { width = 51, height = 71 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "exo_66.png",
				spriteColorRect = { x = 0, y = 0, width = 25, height = 71 },
				textureRect = { x = 1430, y = 88, width = 25, height = 71 },
				spriteSourceSize = { width = 25, height = 71 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "exo_67.png",
				spriteColorRect = { x = 0, y = 0, width = 26, height = 71 },
				textureRect = { x = 1457, y = 88, width = 26, height = 71 },
				spriteSourceSize = { width = 26, height = 71 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "exo_68.png",
				spriteColorRect = { x = 0, y = 0, width = 28, height = 71 },
				textureRect = { x = 1485, y = 88, width = 28, height = 71 },
				spriteSourceSize = { width = 28, height = 71 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "exo_69.png",
				spriteColorRect = { x = 0, y = 0, width = 23, height = 71 },
				textureRect = { x = 1515, y = 88, width = 23, height = 71 },
				spriteSourceSize = { width = 23, height = 71 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "exo_70.png",
				spriteColorRect = { x = 0, y = 0, width = 38, height = 71 },
				textureRect = { x = 1540, y = 88, width = 38, height = 71 },
				spriteSourceSize = { width = 38, height = 71 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "exo_71.png",
				spriteColorRect = { x = 0, y = 0, width = 45, height = 71 },
				textureRect = { x = 1580, y = 88, width = 45, height = 71 },
				spriteSourceSize = { width = 45, height = 71 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "exo_72.png",
				spriteColorRect = { x = 0, y = 0, width = 37, height = 71 },
				textureRect = { x = 1627, y = 88, width = 37, height = 71 },
				spriteSourceSize = { width = 37, height = 71 },
				spriteTrimmed = false,
				textureRotated = false
			},
		}
	}
end
return SpriteSheet

