-- This file is for use with Corona Game Edition
-- 
-- The function getSpriteSheetData() returns a table suitable for importing using sprite.newSpriteSheetFromData()
-- 
-- This file is automatically generated with TexturePacker (http://www.codeandweb.com/texturepacker). Do not edit
-- $TexturePacker:SmartUpdate:a1f445c6ca4d77488ea17842eff979c8:91403e1ca4f0a0b63d62d844302b8e97:b43307fe10c40c623eb3691a7b77358d$
-- 
-- Usage example:
--        local sheetData = require "ThisFile.lua"
--        local data = sheetData.getSpriteSheetData()
--        local spriteSheet = sprite.newSpriteSheetFromData( "Untitled.png", data )
-- 
-- For more details, see http://developer.anscamobile.com/content/game-edition-sprite-sheets

local SpriteSheet = {}
SpriteSheet.getSpriteSheetData = function ()
	return {
		frames = {
			{
				name = "0.png",
				spriteColorRect = { x = 0, y = 0, width = 200, height = 300 },
				textureRect = { x = 2, y = 2, width = 200, height = 300 },
				spriteSourceSize = { width = 200, height = 300 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "1.png",
				spriteColorRect = { x = 0, y = 0, width = 200, height = 300 },
				textureRect = { x = 204, y = 2, width = 200, height = 300 },
				spriteSourceSize = { width = 200, height = 300 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "2.png",
				spriteColorRect = { x = 0, y = 0, width = 200, height = 300 },
				textureRect = { x = 406, y = 2, width = 200, height = 300 },
				spriteSourceSize = { width = 200, height = 300 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "3.png",
				spriteColorRect = { x = 0, y = 0, width = 200, height = 300 },
				textureRect = { x = 608, y = 2, width = 200, height = 300 },
				spriteSourceSize = { width = 200, height = 300 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "4.png",
				spriteColorRect = { x = 0, y = 0, width = 200, height = 300 },
				textureRect = { x = 810, y = 2, width = 200, height = 300 },
				spriteSourceSize = { width = 200, height = 300 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "5.png",
				spriteColorRect = { x = 0, y = 0, width = 200, height = 300 },
				textureRect = { x = 1012, y = 2, width = 200, height = 300 },
				spriteSourceSize = { width = 200, height = 300 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "6.png",
				spriteColorRect = { x = 0, y = 0, width = 200, height = 300 },
				textureRect = { x = 1214, y = 2, width = 200, height = 300 },
				spriteSourceSize = { width = 200, height = 300 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "7.png",
				spriteColorRect = { x = 0, y = 0, width = 200, height = 300 },
				textureRect = { x = 1416, y = 2, width = 200, height = 300 },
				spriteSourceSize = { width = 200, height = 300 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "8.png",
				spriteColorRect = { x = 0, y = 0, width = 200, height = 300 },
				textureRect = { x = 1618, y = 2, width = 200, height = 300 },
				spriteSourceSize = { width = 200, height = 300 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "9.png",
				spriteColorRect = { x = 0, y = 0, width = 200, height = 300 },
				textureRect = { x = 1820, y = 2, width = 200, height = 300 },
				spriteSourceSize = { width = 200, height = 300 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "A.png",
				spriteColorRect = { x = 0, y = 0, width = 200, height = 300 },
				textureRect = { x = 2, y = 304, width = 200, height = 300 },
				spriteSourceSize = { width = 200, height = 300 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "B.png",
				spriteColorRect = { x = 0, y = 0, width = 200, height = 300 },
				textureRect = { x = 204, y = 304, width = 200, height = 300 },
				spriteSourceSize = { width = 200, height = 300 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "C.png",
				spriteColorRect = { x = 0, y = 0, width = 200, height = 300 },
				textureRect = { x = 406, y = 304, width = 200, height = 300 },
				spriteSourceSize = { width = 200, height = 300 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "D.png",
				spriteColorRect = { x = 0, y = 0, width = 200, height = 300 },
				textureRect = { x = 608, y = 304, width = 200, height = 300 },
				spriteSourceSize = { width = 200, height = 300 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "E.png",
				spriteColorRect = { x = 0, y = 0, width = 200, height = 300 },
				textureRect = { x = 810, y = 304, width = 200, height = 300 },
				spriteSourceSize = { width = 200, height = 300 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "F.png",
				spriteColorRect = { x = 0, y = 0, width = 200, height = 300 },
				textureRect = { x = 1012, y = 304, width = 200, height = 300 },
				spriteSourceSize = { width = 200, height = 300 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "G.png",
				spriteColorRect = { x = 0, y = 0, width = 200, height = 300 },
				textureRect = { x = 1214, y = 304, width = 200, height = 300 },
				spriteSourceSize = { width = 200, height = 300 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "H.png",
				spriteColorRect = { x = 0, y = 0, width = 200, height = 300 },
				textureRect = { x = 1416, y = 304, width = 200, height = 300 },
				spriteSourceSize = { width = 200, height = 300 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "I.png",
				spriteColorRect = { x = 0, y = 0, width = 200, height = 300 },
				textureRect = { x = 1618, y = 304, width = 200, height = 300 },
				spriteSourceSize = { width = 200, height = 300 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "J.png",
				spriteColorRect = { x = 0, y = 0, width = 200, height = 300 },
				textureRect = { x = 1820, y = 304, width = 200, height = 300 },
				spriteSourceSize = { width = 200, height = 300 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "K.png",
				spriteColorRect = { x = 0, y = 0, width = 200, height = 300 },
				textureRect = { x = 2, y = 606, width = 200, height = 300 },
				spriteSourceSize = { width = 200, height = 300 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "L.png",
				spriteColorRect = { x = 0, y = 0, width = 200, height = 300 },
				textureRect = { x = 204, y = 606, width = 200, height = 300 },
				spriteSourceSize = { width = 200, height = 300 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "M.png",
				spriteColorRect = { x = 0, y = 0, width = 200, height = 300 },
				textureRect = { x = 406, y = 606, width = 200, height = 300 },
				spriteSourceSize = { width = 200, height = 300 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "N.png",
				spriteColorRect = { x = 0, y = 0, width = 200, height = 300 },
				textureRect = { x = 608, y = 606, width = 200, height = 300 },
				spriteSourceSize = { width = 200, height = 300 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "O.png",
				spriteColorRect = { x = 0, y = 0, width = 200, height = 300 },
				textureRect = { x = 810, y = 606, width = 200, height = 300 },
				spriteSourceSize = { width = 200, height = 300 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "P.png",
				spriteColorRect = { x = 0, y = 0, width = 200, height = 300 },
				textureRect = { x = 1012, y = 606, width = 200, height = 300 },
				spriteSourceSize = { width = 200, height = 300 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "R.png",
				spriteColorRect = { x = 0, y = 0, width = 200, height = 300 },
				textureRect = { x = 1214, y = 606, width = 200, height = 300 },
				spriteSourceSize = { width = 200, height = 300 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "S.png",
				spriteColorRect = { x = 0, y = 0, width = 200, height = 300 },
				textureRect = { x = 1416, y = 606, width = 200, height = 300 },
				spriteSourceSize = { width = 200, height = 300 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "T.png",
				spriteColorRect = { x = 0, y = 0, width = 200, height = 300 },
				textureRect = { x = 1618, y = 606, width = 200, height = 300 },
				spriteSourceSize = { width = 200, height = 300 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "U.png",
				spriteColorRect = { x = 0, y = 0, width = 200, height = 300 },
				textureRect = { x = 1820, y = 606, width = 200, height = 300 },
				spriteSourceSize = { width = 200, height = 300 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "V.png",
				spriteColorRect = { x = 0, y = 0, width = 200, height = 300 },
				textureRect = { x = 2, y = 908, width = 200, height = 300 },
				spriteSourceSize = { width = 200, height = 300 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "W.png",
				spriteColorRect = { x = 0, y = 0, width = 200, height = 300 },
				textureRect = { x = 204, y = 908, width = 200, height = 300 },
				spriteSourceSize = { width = 200, height = 300 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "X.png",
				spriteColorRect = { x = 0, y = 0, width = 200, height = 300 },
				textureRect = { x = 406, y = 908, width = 200, height = 300 },
				spriteSourceSize = { width = 200, height = 300 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "Y.png",
				spriteColorRect = { x = 0, y = 0, width = 200, height = 300 },
				textureRect = { x = 608, y = 908, width = 200, height = 300 },
				spriteSourceSize = { width = 200, height = 300 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "Z.png",
				spriteColorRect = { x = 0, y = 0, width = 200, height = 300 },
				textureRect = { x = 810, y = 908, width = 200, height = 300 },
				spriteSourceSize = { width = 200, height = 300 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "colon.png",
				spriteColorRect = { x = 0, y = 0, width = 200, height = 300 },
				textureRect = { x = 1012, y = 908, width = 200, height = 300 },
				spriteSourceSize = { width = 200, height = 300 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "exclamation.png",
				spriteColorRect = { x = 0, y = 0, width = 200, height = 300 },
				textureRect = { x = 1214, y = 908, width = 200, height = 300 },
				spriteSourceSize = { width = 200, height = 300 },
				spriteTrimmed = false,
				textureRotated = false
			},
		}
	}
end
return SpriteSheet

